Searchform Item Placeholder Visibility based on Label - Updated
aazztech/directorist pull request #2152
Opened 2024-11-30 06:55 UTC by iamibrahimriaz

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Security fix
- [x] Improvement
- [ ] New Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Text changes
- [ ] Other... Please describe:

## Description
How to reproduce the issue or how to test the changes

**Before:** 
When Label is empty: https://prnt.sc/UfFWUeZVL-Kc 

**After:**
When Label is empty: https://prnt.sc/rNEXJThM00u3 

## Any linked issues
Fixes #

## Checklist

- [x] My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

2024-12-01 06:26 UTC, vairafiq approved these changes

2024-12-01 06:26 UTC, vairafiq commented on includes/asset-loader/localized_data.php
> +			'default_label'         	  => __( 'Label', 'directorist' ),
stuff needs to be specific please change it to `search_form_default_label` and `search_form_default_placeholder`

2024-12-01 06:26 UTC, vairafiq commented on templates/search-form/fields/location.php
>  	?>
need to change the template version at the top `8.0.8.1`

2024-12-01 06:28 UTC, vairafiq requested changes

2024-12-01 06:28 UTC, vairafiq commented on templates/search-form/fields/location.php
>  	?>
Need to change `@version`

2024-12-01 07:04 UTC, iamibrahimriaz commented on includes/asset-loader/localized_data.php
> +			'default_label'         	  => __( 'Label', 'directorist' ),
Changed

2024-12-01 07:04 UTC, iamibrahimriaz commented on templates/search-form/fields/location.php
>  	?>
Changed

2024-12-05 16:35 UTC, obiPlabon requested changes

2024-12-05 16:35 UTC, obiPlabon commented on templates/search-form/fields/location.php
> + * @version 8.0.8.1
Version 8.0.9

2024-12-12 02:29 UTC, vairafiq approved these changes

2024-12-15 06:44 UTC, obiPlabon approved these changes

2024-12-15 06:44 UTC, merged