Active Class on Viewas Item - Added
aazztech/directorist pull request #2154
Opened 2024-12-03 09:39 UTC by iamibrahimriaz

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Security fix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Text changes
- [ ] Other... Please describe:

## Description
How to reproduce the issue or how to test the changes

**Before:**
https://prnt.sc/DgkRtaAAWS-m 

**After:**
https://prnt.sc/zYkeFQG55PLr 

## Any linked issues
Fixes #

## Checklist

- [x] My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

2024-12-05 16:40 UTC, obiPlabon requested changes

2024-12-05 16:40 UTC, obiPlabon commented on assets/src/js/public/search-form.js
> +            let parent = $(this).closest('.directorist-viewas');
https://api.jquery.com/siblings/

Use this and you'll be able to reduce code.

2024-12-12 02:30 UTC, vairafiq approved these changes

2024-12-12 03:14 UTC, iamibrahimriaz commented on assets/src/js/public/search-form.js
> +            let parent = $(this).closest('.directorist-viewas');
OK

2024-12-15 06:47 UTC, obiPlabon approved these changes

2024-12-15 06:47 UTC, merged