Importer hooks
aazztech/directorist pull request #2161
Opened 2024-12-07 06:19 UTC by HeyMehedi

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Security fix
- [x] Improvement
- [ ] New Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Text changes
- [ ] Other... Please describe:

## Description
Added hooks for Gallery Image importing,

## Any linked issues
Fixes #

## Checklist

- [ ] My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

2024-12-30 10:41 UTC, Armanul46 commented
Looks good

2024-12-31 04:40 UTC, vairafiq requested changes
1. Need to add hook doc block with @since and other necessary
2. Need to pass the current loop item so that anyone can process data based on the loop. Otherwise, the hooks are quite useless

2024-12-31 05:01 UTC, vairafiq requested changes

2024-12-31 05:01 UTC, vairafiq commented on includes/classes/class-tools.php
> +			do_action( 'directorist_before_listings_import' );
Better to pass all the request data `do_action('directorist_before_listings_import', $_POST);`

2024-12-31 05:02 UTC, vairafiq commented on includes/classes/class-tools.php
> +			do_action( 'directorist_before_listings_import' );
do the same for both before after hooks

2024-12-31 05:03 UTC, HeyMehedi commented
> 2. Need to pass the current loop item so that anyone can process data based on the loop. Otherwise, the hooks are quite useless

Thank you for your feedback! I see your point about passing the current loop item to hooks, but I’d like to clarify that there are already hooks placed inside the loop for this purpose. Specifically, the _directorist_import_listing_starts_ and _directorist_listing_imported_ hooks allow developers to process individual loop items effectively during the import process.

The hooks you mentioned—_directorist_before_listings_import_ and _directorist_after_listings_import_—are intentionally placed outside the loop. They serve a different purpose, such as initializing or finalizing tasks related to the entire import process, rather than processing individual items.

If you’re looking for something specific that isn’t addressed by the current hooks, feel free to share more details. I’d be happy to explore further improvements. Thanks for raising this point! 😊

2024-12-31 05:14 UTC, HeyMehedi commented on includes/classes/class-tools.php
> +			do_action( 'directorist_before_listings_import' );
Since `$_POST` is processed before the loop, I have passed the sanitized `$posts` instead of directly using the raw `$_POST`. Additionally, I have included `$data` in the last hook. I believe this approach should be good to go.

2024-12-31 05:34 UTC, vairafiq approved these changes

2024-12-31 05:34 UTC, merged