apply filter - directorist_delete_listings_from_dashboard
aazztech/directorist pull request #489
Opened 2021-10-10 09:23 UTC by MahfuzulAlam

Introduce a hook "directorist_delete_listings_from_dashboard" to determine the status of the deleted listings from the dashboard whether it is going to trash or deleted forever.

https://i.imgur.com/oU5M5L7.png

@return 'delete' to delete forever or 'anything' to send the listing to the trash

2021-10-14 08:15 UTC, MahfuzulAlam reviewed
This filter will help the user to overwrite the default social link options.

2021-12-21 03:23 UTC, kowsar89 requested changes
1. Please rename the following hooks:
```
directorist_default_social_links => directorist_social_items
directorist_delete_listings_from_dashboard => directorist_listing_delete_or_trash
```
2. Fix merge conflict
@MahfuzulAlam

2021-12-27 05:45 UTC, vairafiq approved these changes, later dismissed
Looks good

2021-12-27 06:08 UTC, kowsar89 requested changes

2021-12-27 06:08 UTC, kowsar89 commented on includes/model/ListingDashboard.php
>  	public function listing_task( $task, $taskdata ){
$task variable isn't used anywhere in the code!

2022-02-06 06:45 UTC, vairafiq approved these changes
tested

2022-02-06 09:20 UTC, kowsar89 requested changes

2022-02-06 09:20 UTC, kowsar89 commented on includes/model/ListingDashboard.php
> +		}else{
$task can be anything in future- like 'delete', 'update' etc, so "else" command should not be used here to avoid bugs in future. Only 'if' is allowed

2022-07-27 02:43 UTC, closed without merging